### ISSUE TITLE
heat map generation

### ISSUE THREAD

**Issue by feiyangsb** [QingyuZhao/VAE-for-Regression#1]
Hello @QingyuZhao ,
I am reading your paper now and very interested in it. In your paper, you generate a "heat map" indicating the location of voxels that contribute to faithful prediction. But, the codes to generate this "heat map" is not in your repo. I am just wondering if it is possible to share these codes or give me the idea of how to generate that (maybe it's a dumb question). 
Thanks,
Feiyang

**Comment by QingyuZhao** [comment]
If it is the VAE regression work that you are asking about, the visualization is the Jacobian determinant.

If you are talking about the "heat map" indicating the location of voxels that contribute to faithful prediction. Please find my other repo,
https://github.com/QingyuZhao/Confounder-Aware-CNN-Visualization

Best,
-Q
________________________________

**Comment by feiyangsb** [comment]
Thanks!!
